name: Mebel CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches : [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            remote-host: http://46.8.43.42
            remote-user: root
            remote-port: 8080 # (optional)
            source: target/mebel2-0.0.1-SNAPSHOT.jar
            target: http://46.8.43.42/root/Programmer
            args: -rltgoDzvO # (optional)

          
          

