name: Mebel CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches : [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: ubuntu
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#         ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        remote-user: root
        server-ip: 46.8.43.42:8080
        local-path: 'target/*.jar'
        remote-path: '/root/mebel2-0.0.1-SNAPSHOT.jar'
